Update requirements.txt
unabele to complie and install psycopg2-binary

(fastenv) PS D:\rigelsoft\curd_fastapi> pip install psycopg2-binary
Requirement already satisfied: psycopg2-binary in d:\rigelsoft\curd_fastapi\fastenv\lib\site-packages (2.9.3)
(fastenv) PS D:\rigelsoft\curd_fastapi> pip install agatereports
Collecting agatereports
  Using cached agatereports-0.0.1-py3-none-any.whl (47 kB)
Collecting reportlab>=3.4.0
  Using cached reportlab-3.6.11-cp39-cp39-win_amd64.whl (2.3 MB)
Requirement already satisfied: mysql-connector-python>=8.0 in d:\rigelsoft\curd_fastapi\fastenv\lib\site-packages (from agatereports) (8.0.29)
Collecting psycopg2-binary<2.8,>=2.7
  Using cached psycopg2-binary-2.7.7.tar.gz (428 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating C:\Users\deepa\AppData\Local\Temp\pip-pip-egg-info-_gto27r9\psycopg2_binary.egg-info
      writing C:\Users\deepa\AppData\Local\Temp\pip-pip-egg-info-_gto27r9\psycopg2_binary.egg-info\PKG-INFO
      writing dependency_links to C:\Users\deepa\AppData\Local\Temp\pip-pip-egg-info-_gto27r9\psycopg2_binary.egg-info\dependency_links.txt
      writing top-level names to C:\Users\deepa\AppData\Local\Temp\pip-pip-egg-info-_gto27r9\psycopg2_binary.egg-info\top_level.txt
      writing manifest file 'C:\Users\deepa\AppData\Local\Temp\pip-pip-egg-info-_gto27r9\psycopg2_binary.egg-info\SOURCES.txt'
     
      Error: pg_config executable not found.
     
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
     
          python setup.py build_ext --pg-config /path/to/pg_config build ...
     
      or with the pg_config option in 'setup.cfg'.
     
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
     
      For further information please check the 'doc/src/install.rst' file (also at
      <http://initd.org/psycopg/docs/install.html>).
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.